#!/usr/bin/env python
# -*- coding: utf-8 -*-

Import('env')

from util import match_patterns, minifiables, filter_files
from fnmatch import fnmatch
from os.path import basename
from filesystem import walk_dir

SRC_DIR = './'
DEST_DIR = '../' + env['MEDIA_DEST_DIR'] + '/'

SCRIPT_FILES = Split("""
    script/base.js
    script/recruiters.js
    script/lib/chickoojs/src/jquery/color/jquery.color.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.tabs-1.0.3.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable-1.1.1.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable.autoscroll-1.0.1.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable.circular-0.5.1.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable.navigator-1.0.1.js
    script/lib/chickoojs/src/jquery/easing/jquery.easing.1.3.js
    script/lib/chickoojs/src/jquery/hoverIntent/jquery.hoverIntent.js
    script/lib/chickoojs/src/jquery/jquery-1.3.2.js

    script/lib/chickoojs/src/json2.js
    script/lib/rightjs/core/right-src.js
    script/lib/rightjs/ui/right-calendar-src.js
    script/lib/rightjs/ui/right-tooltips-src.js
    script/lib/rightjs/ui/right-lightbox-src.js
    script/lib/chickoojs/src/jquery/form/jquery.form.js
    script/lib/chickoojs/src/jquery/validate/jquery.validate.js
    script/admin/common.js
    script/admin/people.js
    script/admin/news.js
    script/admin/jobs.js
    script/jquery.lightbox-0.5.js
""")
#SCRIPT_FILES = ["script/" + f for f in SCRIPT_FILES]

IMAGE_FILES = Split("""
    image/background/rays.png
    image/logo_small.png
    image/logo_small_stroked.png
    image/logo_shield_small.png
    image/background/overlay_black.png
    image/background/separator.png
    image/img_shadow.png
    image/background/close.png
    image/background/footer.png
    image/contact_us.png
    image/altiba/altiba-1.jpg
    image/altiba/altiba-2.jpg
    image/altiba/altiba-3.jpg
    image/altiba/altiba-4.jpg
    image/altiba/altiba-5.jpg
    image/altiba/altiba-6.jpg
    image/altiba/altiba-7.jpg
    image/altiba/thumbnail/altiba-1.jpg
    image/altiba/thumbnail/altiba-2.jpg
    image/altiba/thumbnail/altiba-3.jpg
    image/altiba/thumbnail/altiba-4.jpg
    image/altiba/thumbnail/altiba-5.jpg
    image/altiba/thumbnail/altiba-6.jpg
    image/altiba/thumbnail/altiba-7.jpg
    image/altida/altida-1.jpg
    image/altida/altida-2.jpg
    image/altida/altida-3.jpg
    image/altida/altida-4.jpg
    image/altida/altida-5.jpg
    image/altida/altida-6.jpg
    image/altida/thumbnail/altida-1.jpg
    image/altida/thumbnail/altida-2.jpg
    image/altida/thumbnail/altida-3.jpg
    image/altida/thumbnail/altida-4.jpg
    image/altida/thumbnail/altida-5.jpg
    image/altida/thumbnail/altida-6.jpg
    image/altiha/altiha-1.jpg
    image/altiha/altiha-2.jpg
    image/altiha/altiha-3.jpg
    image/altiha/altiha-4.jpg
    image/altiha/altiha-5.jpg
    image/altiha/thumbnail/altiha-1.jpg
    image/altiha/thumbnail/altiha-2.jpg
    image/altiha/thumbnail/altiha-3.jpg
    image/altiha/thumbnail/altiha-4.jpg
    image/altiha/thumbnail/altiha-5.jpg
    image/alumni/adil_malia.jpg
    image/alumni/maitra.jpg
    image/alumni/makarand_khatavkar.jpg
    image/alumni/santrupt.jpg
    image/background/button_overlay.png
    image/icon/star.png
    image/background/textfield_normal.png
    image/background/polaroid.png
    image/background/textfield_readonly.png
    image/background/grunge_paper.jpg
    image/icon/favicon.png
    image/lightbox/lightbox-blank.gif
    image/lightbox/lightbox-btn-close.gif
    image/lightbox/lightbox-btn-next.gif
    image/lightbox/lightbox-btn-prev.gif
    image/lightbox/lightbox-ico-loading.gif
    
""")

CSS_FILES = Split("""
    css/generic.css
    css/screen.css
    css/google_talk.css
    css/jquery.lightbox-0.5.css
""")

# Do not include IMAGE files in here.
# Please include them in IMAGE_FILES above.
# If you would like images to be copied "as is" without
# any optimizations, then you may include them here.
PLAIN_COPIES = SCRIPT_FILES + CSS_FILES + Split("""
    robots.txt
    crossdomain.xml
""")

PLAIN_COPY_DIRECTORIES = Split("""

""")

# Recursively add all the files in the directories to files to copy.
for directory in set(PLAIN_COPY_DIRECTORIES):
    files = [f[len(SRC_DIR):] for f in walk_dir(SRC_DIR + directory)]
    PLAIN_COPIES.extend(files)

# Plain copies.
for f in set(PLAIN_COPIES):
    env.Command(DEST_DIR + f, SRC_DIR + f, Copy("$TARGET", "$SOURCE"))

# Optimize graphics
for f in IMAGE_FILES:
    filename = str(f)
    if match_patterns(filename, patterns=['*.png']):
        env.OptimizePNG(DEST_DIR + f, SRC_DIR + f)
    elif match_patterns(filename, patterns=['*.jpg', '*.jpeg']):
        env.OptimizeJPEG(DEST_DIR + f, SRC_DIR + f)
    else:
        env.Command(DEST_DIR + f, SRC_DIR + f, Copy("$TARGET", "$SOURCE"))


# Stitching graphics together
stitched_images = [
        dict(
            target='image/logo_with_shield.png',
            sources=Split("""
                image/logo_shield.png
                image/logo_hrm_text.png
            """),
            orientation='horizontal'
            ),
        dict(
            target='image/recruiter_logos.jpg',
            sources=Split("""
                image/edited_logos/accenture.jpg
                image/edited_logos/asianpaints.jpg
                image/edited_logos/astrazeneca.jpg
                image/edited_logos/bennettcoleman.jpg
                image/edited_logos/bpcl.jpg
                image/edited_logos/cadbury.jpg
                image/edited_logos/citibank.jpg
                image/edited_logos/cocacola.jpg

                image/edited_logos/colgatepalmolive.jpg
                image/edited_logos/countrywidefinances.jpg
                image/edited_logos/deutschbank.jpg
                image/edited_logos/drreddy.jpg
                image/edited_logos/ernstyoung.jpg
                image/edited_logos/fidelity.jpg
                image/edited_logos/firstsource.jpg
                image/edited_logos/geshipping.jpg

                image/edited_logos/google.jpg
                image/edited_logos/hindustanunilever.jpg
                image/edited_logos/honeywell.jpg
                image/edited_logos/hpcl.jpg
                image/edited_logos/hsbc.jpg
                image/edited_logos/ibm.jpg
                image/edited_logos/iciciprudentials.jpg
                image/edited_logos/intel.jpg

                image/edited_logos/johnsonandjohnson.jpg
                image/edited_logos/jpmorganchase.jpg
                image/edited_logos/kpmg.jpg
                image/edited_logos/mahindra.jpg
                image/edited_logos/marico.jpg
                image/edited_logos/mercer.jpg
                image/edited_logos/microsoft.jpg
                image/edited_logos/motorola.jpg

                image/edited_logos/nestle.jpg
                image/edited_logos/nokia.jpg
                image/edited_logos/novartis.jpg
                image/edited_logos/oracle.jpg
                image/edited_logos/patni.jpg
                image/edited_logos/pepsi.jpg
                image/edited_logos/pfizer.jpg
                image/edited_logos/procterandgamble.jpg

                image/edited_logos/pwc.jpg
                image/edited_logos/ranbaxy.jpg
                image/edited_logos/rpg.jpg
                image/edited_logos/sap.jpg
                image/edited_logos/siemensindia.jpg
                image/edited_logos/standardchartered.jpg
                image/edited_logos/sterlite.jpg
                image/edited_logos/taj.jpg

                image/edited_logos/tata.jpg
                image/edited_logos/wipro.jpg
                image/edited_logos/yahoo.jpg
                image/edited_logos/barista.jpg
                image/edited_logos/bindasmovies.jpg

                image/edited_logos/bru.jpg
                image/edited_logos/capgemini.jpg
                image/edited_logos/emkay.jpg
                image/edited_logos/fame.jpg
                image/edited_logos/humancapital.jpg
                image/edited_logos/indiadevelopmentgateway.jpg
                
                image/edited_logos/intellcap.jpg
                image/edited_logos/lbw.jpg
                image/edited_logos/mafoi.jpg
                image/edited_logos/naukri.jpg
                image/edited_logos/nen.jpg
                image/edited_logos/pagalguy.jpg
                
                image/edited_logos/nielsen.jpg
                image/edited_logos/powerhorse.jpg
                image/edited_logos/radiomirchi.jpg
                image/edited_logos/rcf.jpg
                image/edited_logos/shrmindia.jpg
                image/edited_logos/syntel.jpg
                
                image/edited_logos/utvi.jpg
                image/edited_logos/timesascent.jpg
                
                
            """),
            orientation='horizontal'
            ),
]
for stitch in stitched_images:
    func = env.HStitchImages if stitch.get('orientation', 'horizontal') == 'horizontal' else env.VStitchImages
    func(DEST_DIR + stitch['target'], [SRC_DIR + f for f in stitch['sources']])


# Minification of the generated CSS and JS files.
MINIFIABLE_FILES = SCRIPT_FILES + CSS_FILES + Split("""

""")

# Exclude these files specifically from minification.
NON_MINIFIABLE_FILES = Split("""

""")


# Don't minify all files in one command.  Minify them separately.
# It keeps build times small.
for f in minifiables(MINIFIABLE_FILES, NON_MINIFIABLE_FILES):
    filepath = DEST_DIR + str(f)
    env.YuiCompressorMinify(filepath)
    #if fnmatch(basename(filepath), '*.js'):
    #    env.JsminMinify(filepath)

# Combine these JavaScript files and create a common js.
#
# Warning:  THE ORDER MATTERS.
#
#script/lib/cufon/js/cufon.js
#script/angelina_400.font.js
    #script/lib/chickoojs/src/jquery/color/jquery.color.js
COMMON_JS_FILES =  Split("""
    script/lib/chickoojs/src/jquery/easing/jquery.easing.1.3.js
    script/lib/chickoojs/src/jquery/hoverIntent/jquery.hoverIntent.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.tabs-1.0.3.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable-1.1.1.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable.autoscroll-1.0.1.js
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.scrollable.circular-0.5.1.js
    script/base.js
""")
COMMON_JS_FILES = [SRC_DIR + f for f in COMMON_JS_FILES]
lib_common_js = env.Concatenate([DEST_DIR + 'script/common.js'], COMMON_JS_FILES)
env.YuiCompressorMinify(lib_common_js)
#env.JsminMinify(lib_common_js)

LIB_ADMIN_COMMON_JS_FILES =  Split("""
    script/lib/chickoojs/src/json2.js
    script/lib/rightjs/core/right-src.js
    script/lib/rightjs/ui/right-calendar-src.js
    script/lib/rightjs/ui/right-tooltips-src.js
    script/lib/rightjs/ui/right-lightbox-src.js
    script/lib/chickoojs/src/jquery/form/jquery.form.js
    script/lib/chickoojs/src/jquery/validate/jquery.validate.js
    script/admin/common.js
    """)
LIB_ADMIN_COMMON_JS_FILES = [SRC_DIR + f for f in LIB_ADMIN_COMMON_JS_FILES]
lib_admin_common_js = env.Concatenate([DEST_DIR + 'script/lib/admin-common.js'], LIB_ADMIN_COMMON_JS_FILES)
env.YuiCompressorMinify(lib_admin_common_js)

LIB_INDEX_JS_FILES =  Split("""
    script/lib/chickoojs/src/jquery/tools/1.1.1/tools.flashembed-1.0.4.js
    script/index.js
""")
LIB_INDEX_JS_FILES = [SRC_DIR + f for f in LIB_INDEX_JS_FILES]
lib_index_js = env.Concatenate([DEST_DIR + 'script/page/index.js'], LIB_INDEX_JS_FILES)
env.YuiCompressorMinify(lib_index_js)
env.JsminMinify(lib_index_js)

LIB_GALLERY_JS_FILES =  Split("""
    script/jquery.lightbox-0.5.js
    script/gallery.js
""")
LIB_GALLERY_JS_FILES = [SRC_DIR + f for f in LIB_GALLERY_JS_FILES]
lib_gallery_js = env.Concatenate([DEST_DIR + 'script/page/gallery.js'], LIB_GALLERY_JS_FILES)
env.YuiCompressorMinify(lib_gallery_js)
#env.JsminMinify(lib_gallery_js)



LIB_ACHIEVEMENT_JS_FILES =  Split("""
    script/jquery.innerfade.js
    script/achievement.js
""")
LIB_ACHIEVEMENT_JS_FILES = [SRC_DIR + f for f in LIB_ACHIEVEMENT_JS_FILES]
lib_achievement_js = env.Concatenate([DEST_DIR + 'script/page/achievement.js'], LIB_ACHIEVEMENT_JS_FILES)
env.YuiCompressorMinify(lib_achievement_js)
env.JsminMinify(lib_achievement_js)



admin_all_css_files =  Split("""
    css/generic.css
    css/admin.css
    """)
admin_all_css_files = [SRC_DIR + f for f in admin_all_css_files]
admin_all_css = env.Concatenate([DEST_DIR + 'css/admin-all.css'], admin_all_css_files)
env.YuiCompressorMinify(admin_all_css)

screen_all_css_files =  Split("""
    css/generic.css
    css/screen.css
    """)
screen_all_css_files = [SRC_DIR + f for f in screen_all_css_files]
screen_all_css = env.Concatenate([DEST_DIR + 'css/screen-all.css'], screen_all_css_files)
env.YuiCompressorMinify(screen_all_css)

# Include licenses.
#c3 = env.Concatenate([DEST_DIR + 'script/lib/all-min.js'], [
#    DEST_DIR + 'script/LICENSES',
#    DEST_DIR + 'script/lib/all_o-min.js',
#])

