#!/usr/bin/env python
# -*- coding: utf-8 -*-

from google.appengine.ext import db

RECRUITERS = {
    "asian-paints": {"name": "Asian Paints", "url": "http://asianpaints.com/"},
    "astrazeneca": {"name": "Astrazeneca", "url": "http://astrazeneca.com/"},
    "bennett-coleman": {"name": "Bennett Coleman", "url": "http://www.timesofindia.com/"},
    "countrywide-finances": {"name": "Countrywide Finances", "url": "http://my.countrywide.com/"},
    "siemens-india": {"name": "Siemens India", "url": "http://w1.siemens.com/"},
    "accenture": {"name": "Accenture", "url": "http://www.accenture.com/"},
    "bpcl": {"name": "Bharat Petroleum", "url": "http://www.bharatpetroleum.com/"},
    "cadbury": {"name": "Cadbury", "url": "http://www.cadburyindia.com/home/index.asp"},
    "citibank": {"name": "Citibank", "url": "http://www.citibank.com/us/home.htm"},
    "coca-cola": {"name": "Coca-Cola", "url": "http://www.coca-cola.com/index.jsp"},
    "colgate-palmolive": {"name": "Colgate Palmolive", "url": "http://www.colgate.co.in/app/Colgate/IN/HomePage.cvsp"},
    "deutsche-bank": {"name": "Deutsche Bank", "url": "http://www.db.com"},
    "dr-reddy": {"name": "Dr. Reddy", "url": "http://www.drreddys.com/"},
    "ernst-young": {"name": "Ernst Young", "url": "http://www.ey.com"},
    "fidelity": {"name": "Fidelity", "url": "http://www.fidelity.co.in/"},
    "google": {"name": "Google", "url": "http://www.google.com"},
    "ge-shipping": {"name": "GE Shipping", "url": "http://www.greatship.com/"},
    "hpcl": {"name": "Hindustan Petroleum", "url": "http://www.hindustanpetroleum.com/"},
    "honeywell": {"name": "Honeywell", "url": "http://www.honeywell.com/"},
    "hsbc": {"name": "HSBC", "url": "http://www.hsbc.co.in/"},
    "ibm": {"name": "IBM", "url": "http://www.ibm.com/"},
    "icici-prudential": {"name": "ICICI Prudential", "url": "http://www.iciciprulife.com/"},
    "kpmg": {"name": "KPMG", "url": "http://www.in.kpmg.com/"},
    "intel": {"name": "Intel", "url": "http://www.intel.com/"},
    "johnson-and-johnson": {"name": "Johnson and Johnson", "url": "http://www.jnj.com/"},
    "jp-morgan-chase": {"name": "JP Morgan Chase", "url": "http://www.jpmorganmf.com/"},
    "mahindra": {"name": "Mahindra", "url": "http://www.mahindra.com/"},
    "marico": {"name": "Marico", "url": "http://www.marico.com/"},
    "mercer": {"name": "Mercer", "url": "http://www.mercer.com/"},
    "microsoft": {"name": "Microsoft", "url": "http://www.microsoft.com/"},
    "motorola": {"name": "Motorola", "url": "http://www.motorola.com/in"},
    "nestle": {"name": "Nestle", "url": "http://www.nestle.com/"},
    "nokia": {"name": "Nokia", "url": "http://www.nokia.com"},
    "novartis": {"name": "Novartis", "url": "http://www.novartis.com/"},
    "oracle": {"name": "Oracle", "url": "http://www.oracle.com/"},
    "patni": {"name": "Patni", "url": "http://www.patni.com/"},
    "pepsi": {"name": "Pepsi", "url": "http://www.pepsi.com/"},
    "pfizer": {"name": "Pfizer", "url": "http://www.pfizer.com/"},
    "procter-and-gamble": {"name": "Procter and Gamble", "url": "http://www.pg.com/"},
    "pwc": {"name": "Price Waterhouse Coopers", "url": "http://www.pwc.com/"},
    "ranbaxy": {"name": "Ranbaxy", "url": "http://www.ranbaxy.com/"},
    "rpg": {"name": "RPG Group", "url": "http://www.rpggroup.com/"},
    "sap": {"name": "SAP", "url": "http://www.sap.com/"},
    "standard-chartered": {"name": "Standard Chartered", "url": "http://www.standardchartered.com/"},
    "sterlite": {"name": "Sterlite", "url": "http://www.sterlite-industries.com/"},
    "taj": {"name": "Taj Hotels", "url": "http://www.tajhotels.com/"},
    "tata": {"name": "TATA", "url": "http://www.tata.com/"},
    "wipro": {"name": "Wipro", "url": "http://www.wipro.com/"},
    "hindustan-unilever": {"name": "Hindustan Unilever", "url": "http://www.www.hul.co.in/"},
    "yahoo": {"name": "Yahoo! Inc.", "url": "http://www.yahoo.com/"},
}
RECRUITERS_ID_URLS = [(identifier, val["url"]) for identifier, val in RECRUITERS.iteritems()]

